name: Build

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths:
      - ".github/workflows/build.yml"
      - "docker/**"
      - "*.sh"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "docker/**"
      - "build.sh"

jobs:
  manylinux2014-mod:
    name: manylinux2014
    runs-on: ubuntu-20.04

    env:
      POLICY: "manylinux2014"
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

      # Setup tags to be used for docker images
      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/manylinux2014

      # Login to Github Packages
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
  
      - uses: docker/setup-qemu-action@v1
        id: qemu
        with:
          platforms: linux/ppc64le,linux/arm64
  
      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          push: True
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/ppc64le,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
