name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - manylinux1
    paths:
      - ".github/workflows/build.yml"
      - "docker/**"
      - "*.sh"
  pull_request:
    branches:
      - manylinux1

jobs:
  build-push:
    name: manylinux1_x86_64
    runs-on: ubuntu-20.04

    env:
      PLATFORM: x86_64
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2
      - name: Prefetch tarballs
        # Tarballs are prefetched outside the container since CentOS 5 has very old tools
        run: |
          docker/build_scripts/prefetch.sh perl openssl curl cacert

      # Setup tags to be used for docker images
      - uses: docker/metadata-action@v3
        id: docker_meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/manylinux1_x86_64

      # Login to Github Packages
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build and eventually push to registry
      - name: Build and deploy
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile-x86_64
          platforms: linux/amd64
          pull: ${{ github.event_name == 'pull_request' }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

